const KEY_PRIVATE = 'SHOP_CAR_';

const LANGUAGE = `${KEY_PRIVATE}LANGUAGE`;
const TOKEN = `${KEY_PRIVATE}TOKEN`;
const REFRESH_TOKEN = `${KEY_PRIVATE}REFRESH_TOKEN`;
const PROFILE = `${KEY_PRIVATE}PROFILE`;

export default {
  LANGUAGE,
  TOKEN,
  REFRESH_TOKEN,
  PROFILE
};