const KEY_PRIVATE = "SHOP_CAR_";

const LANGUAGE = `${KEY_PRIVATE}LANGUAGE`;
const TOKEN = `${KEY_PRIVATE}TOKEN`;
const REFRESH_TOKEN = `${KEY_PRIVATE}REFRESH_TOKEN`;
const PROFILE = `${KEY_PRIVATE}PROFILE`;
const IS_FILTER = `${KEY_PRIVATE}IS_FILTER`;
const CONFIG_SLIDER = `${KEY_PRIVATE}CONFIG_SLIDER`;
const IS_FILTER_DASHBOARD = `${KEY_PRIVATE}IS_FILTER_DASHBOARD`;
const CONFIG_SLIDER_DASHBOARD = `${KEY_PRIVATE}CONFIG_SLIDER_DASHBOARD`;

export default {
  LANGUAGE,
  TOKEN,
  REFRESH_TOKEN,
  PROFILE,
  IS_FILTER,
  CONFIG_SLIDER,
  IS_FILTER_DASHBOARD,
  CONFIG_SLIDER_DASHBOARD,
};
