const LANGUAGE_VIETNAMESE = 'vi';
const LANGUAGE_ENGLISH = 'en';
const LANGUAGE_KOREAN = 'kr';

const CUSTOMER_SUPPORT_STATUS_DONE = 'done';
const CUSTOMER_SUPPORT_STATUS_IN_PROGRESS = 'in_progress';

export default {
    LANGUAGE_VIETNAMESE,
    LANGUAGE_ENGLISH,
    LANGUAGE_KOREAN,

    CUSTOMER_SUPPORT_STATUS_DONE,
    CUSTOMER_SUPPORT_STATUS_IN_PROGRESS
}